version: '3'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./:/app/
    ports:
      - '5000:5000'
    links:
      - 'mysql:mysqldb'
    depends_on:
      - mysql

  mysql:
    restart: always
    container_name: db
    platform: linux/x86_64
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
